### ISSUE TITLE
add pkgdown website to about page

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot1#1]
Could we add pkgdown website link to the about page? 

Known limitation: 

r version is not controlled and used the most recent version.

**Comment by elong0527** [comment]
Our running environment on RStudio Cloud:

OS: Ubuntu 20.04.2 LTS
R version: R 4.1.0 
repo snapshot: https://mran.microsoft.com/snapshot/2021-08-31

**Comment by lengning** [comment]
done https://rconsortium.github.io/submissions-pilot1/
