### ISSUE TITLE
R version in renv.lock and startup.R not in sync

### ISSUE THREAD

**Issue by ifendo** [RConsortium/submissions-pilot1#10]
hi,
We have R version 3.6.2 recorded in the renv.lock file but this was defined as [R_version <- "4.1.0"] in inst/startup.R file. 

Besides, 'project' misspelled as 'oroject' on line 31 of the inst/startup.R file. thank you.
```
message("Current oroject R package repository:")
```

**Comment by elong0527** [comment]
Thanks! 

The `renv` file has been updated to 4.1.0

The typo has been fixed.
