### ISSUE TITLE
sysfonts package installation on ubuntu 

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot1#17]
@pkwu55 mentioned he can not install this R package on his Ubuntu laptop because of the `sysfonts` package. 

@rpodcast kindly agree to test it from his end.

**Comment by pkwu55** [comment]
BTW I followed the answer in this post to solve my problem https://github.com/r-lib/systemfonts/issues/35

**Comment by elong0527** [comment]
Let's close this one unless new issue is identified.
