### ISSUE TITLE
Update kmplot legend order

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot1#22]
Could you update treatment legend order to placebo, low, high? So we keep consistency of treatment order across all TLFs.

**Comment by SHAESEN2** [comment]
https://github.com/openpharma/visR/issues/311#issue-1115168385

**Comment by SHAESEN2** [comment]
@elong0527 @wangh107 I created a PR in visR to fix the issue of legend labeling. This might come in handy for a future pilot, once the package makes a new CRAN release.

**Comment by elong0527** [comment]
If you can also create a PR in this repo, that would be great! Thanks!

**Comment by SHAESEN2** [comment]
Hey @elong0527 I don't know how to fix it without copying the entire plotting code over which misses the point a bit of using the package. How strongly do you feel about this update versus the amount of work it requires?

**Comment by elong0527** [comment]
We discussed this issue today in the group meeting. We are OK to keep the code as is for this round in the kmplot.
