### ISSUE TITLE
Treatment group for tlf-primary

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot1#23]
Not sure what happen, but the current code still how high does group before the low dose group in tlf-primary.

https://github.com/RConsortium/submissions-pilot1/blob/main/output/tlf-primary.rtf

**Comment by mstackhouse** [comment]
@elong0527 looking - the data are right, it's just the headers that are wrong.

**Comment by mstackhouse** [comment]
Can this now be closed by #24?
