### ISSUE TITLE
can't load `pilot1wrappers` after installation

### ISSUE THREAD

**Issue by kaz462** [RConsortium/submissions-pilot1#30]
Hi @elong0527 
I have trouble loading `pilot1wrappers` after installing it using `remotes::install_github()`, it gets stuck on `library(pilot1wrappers)`.
A similar issue in [pilot3 utilities](https://github.com/RConsortium/submissions-pilot3-utilities), @laxamanaj @DeclanHodges and I also have trouble loading the pilot3 utility package.
Would you kindly check if pilot1 has encountered the same issue before? Thank you!

**Comment by elong0527** [comment]
What's the error message and your running environment?

**Comment by kaz462** [comment]
no warning/error messages, installation was fine, but gets stuck on loading and then freezes
![image](https://github.com/RConsortium/submissions-pilot1/assets/47867131/cc9b76f6-de81-49a9-bd42-938c99b84a9e)

**Comment by kaz462** [comment]
```r
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3 
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] tidyr_1.3.0       utf8_1.2.3        R6_2.5.1          tidyselect_1.2.0  magrittr_2.0.3   
 [6] remotes_2.4.2.1   glue_1.6.2        stringr_1.5.0     tibble_3.2.1      pkgconfig_2.0.3  
[11] dplyr_1.1.2       generics_0.1.3    lifecycle_1.0.3   cli_3.6.1         fansi_1.0.4      
[16] vctrs_0.6.3       compiler_4.3.1    purrr_1.0.1       rstudioapi_0.15.0 tools_4.3.1      
[21] curl_5.0.1        pillar_1.9.0      rlang_1.1.1       stringi_1.7.12 
```

**Comment by fb-elong** [comment]
The pilot project will require additional files that is not available in the binary installed package. 

If you want to rerun the code, you need to follow `renv` workflow. Specifically, run it in following steps: ( suggest to run it from Posit Cloud that have a clean environment.)

- clone the project from github (so you can get all files from this repo)
- install R4.1.3 
- install required R packages using `renv::restore`
- load functions using `devtools::load_all()`. 

If you want to run all analysis in batch, you can run `pkgdown::build_site()` locally.

**Comment by laxamanaj** [comment]
Hi @fb-elong .

Thanks so much for the feedback. We are more interested in knowing the additional files needed for the binary installed package. To have the functions available for other projects, for example. Do you know of a way to find out what  additional files are needed?

Thanks.

Best
Joel

**Comment by elong0527** [comment]
I may not fully understand your intention. If there are functions that needs to be used by other project, it is better to build a standalone R package following Harley's book.

https://r-pkgs.org/whole-game.html

The intention of the pilot project is an analysis project being organized as an R package. The analysis project should be the end node of a package dependency tree. Having other project depends on the pilot project is beyond the scope of this pilot.

**Comment by kaz462** [comment]
Thanks a lot @elong0527 !
We created a standalone R package for [pilot3-utilities](https://github.com/RConsortium/submissions-pilot3-utilities), and most of the functions are from pilot1. However we encountered the loading issue and not sure how to find the root cause, any suggestions on how to resolve this issue?

**Comment by elong0527** [comment]
Thanks for the clarification.

Given it is not an issue for the pilot1, let's close this issue.

Could you create a separate issue in pilot3_utility? I need to take a look that repo to understand what's the problem.

**Comment by kaz462** [comment]
Issue created: https://github.com/RConsortium/submissions-pilot3-utilities/issues/9
Thanks so much for looking into this!
