### ISSUE TITLE
github action update

### ISSUE THREAD

**Issue by fb-elong** [RConsortium/submissions-pilot1#32]
Current github action failed. We need to update the github action files.

**Comment by elong0527** [comment]
@nanxstats, did you see issue like this before? https://github.com/RConsortium/submissions-pilot1/actions/runs/5663450607

**Comment by nanxstats** [comment]
@elong0527 Yes, simply update the GitHub Actions workflow and you should be good:

```r
usethis::use_github_action("pkgdown")
```

The GHA workflows in r-lib/actions have gone through major renovations in the past year or so.
